#FROM node:14.17.0-alpine AS builder
#WORKDIR /usr/src/app
#RUN apk add --no-cache bash git openssh
#
#COPY . .
#
#RUN yarn cache clean && yarn install && yarn run build --production
#
#FROM nginx:alpine
#
#COPY --from=builder /usr/src/app/dist /usr/share/nginx/html
#COPY nginx/default.conf /etc/nginx/conf.d/default.conf


FROM globalmpire/tita-web-deps-cms:deps as builder
WORKDIR /app

# add app
COPY . /app

RUN yarn run build --production

FROM nginx:alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY --from=builder /app/.env /usr/share/nginx/html/.env
COPY --from=builder /app/nginx/default.conf /etc/nginx/conf.d/default.conf

RUN apk add --update nodejs
RUN apk add --update yarn
RUN yarn global add runtime-env-cra
WORKDIR /usr/share/nginx/html
EXPOSE 80
CMD ["/bin/sh", "-c", "runtime-env-cra && nginx -g \"daemon off;\""]
