ARG CONT_IMG_VER=uat
FROM globalmpire/tita-web-deps-cms:uat as builder
WORKDIR /app

# add app
COPY . /app
#COPY .env.uat .env
RUN yarn run build-prod --production

FROM nginx:alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html/
COPY --from=builder /app/.env /usr/share/nginx/html/.env
COPY --from=builder /app/nginx/default.conf /etc/nginx/conf.d/default.conf

RUN apk add --update nodejs
RUN apk add --update yarn
RUN yarn global add runtime-env-cra

WORKDIR /usr/share/nginx/html
EXPOSE 80
CMD ["/bin/sh", "-c", "runtime-env-cra && nginx -g \"daemon off;\""]
