export const PERMISSION_LIST = {
  account: ['list', 'create', 'edit', 'changePassword'],
  customerBuyRent: ['list', 'create', 'edit'],
  customerSellRent: ['list', 'edit'],
  realEstateSell: ['list', 'create', 'edit', 'import', 'export', 'delete', 'assign', 'duplicate'],
  realEstateRent: ['list', 'create', 'edit', 'import', 'export', 'delete', 'assign', 'duplicate'],
  branch: ['list', 'edit', 'delete'],
  province: ['list', 'create', 'edit', 'delete'],
  district: ['list', 'create', 'edit', 'delete'],
  ward: ['list', 'create', 'edit', 'delete'],
  street: ['list', 'create', 'edit', 'delete'],
  realEstateStatus: ['list', 'create', 'edit'],
  realEstateCategory: ['list', 'create', 'edit'],
  report: ['view'],
  setting: ['edit'],
  importExport: ['import', 'export'],
  broker: ['list', 'edit'],
};

export const PERMISSION_TITLE_LIST = {
  branch: 'Quản lý chi nhánh',
  broker: 'Quản lý môi giới',
  account: 'Quản lý thành viên',
  realEstateStatus: 'Quản lý tình trạng BĐS',
  realEstateCategory: 'Quản lý danh mục BĐS',
  realEstateSell: 'Quản lý BĐS bán',
  realEstateRent: 'Quản lý BĐS thuê',
  customerSellRent: 'Quản lý KH bán/cho thuê',
  customerBuyRent: 'Quản lý KH mua/thuê',
  province: 'Quản lý Tỉnh/Thành phố',
  district: 'Quản lý Quận/Huyện',
  ward: 'Quản lý Phường/Xã',
  street: 'Quản lý Đường',
  report: 'Báo cáo vận hành',
  setting: 'Thiết lập chung',
  importExport: 'Quản lý file Import/Export',
};

export const PERMISSION_SUB_TITLE_LIST = {
  branch: 'chi nhánh',
  account: 'thành viên',
  realEstateStatus: 'tình trạng BĐS',
  realEstateCategory: 'danh mục BĐS',
  realEstateSell: 'BĐS bán',
  realEstateRent: 'BĐS thuê',
  customerSellRent: 'KH bán/cho thuê',
  customerBuyRent: 'KH mua/thuê',
  province: 'Tỉnh/Thành phố',
  district: 'Quận/Huyện',
  ward: 'Phường/Xã',
  street: 'Đường',
  report: 'báo cáo vận hành',
  setting: 'thiết lập chung',
  importExport: 'Quản lý file Import/Export',
  broker: 'môi giới bán/cho thuê',
};

export const PERMISSION_TITLE_ACTION = {
  list: 'Xem danh sách tất cả các',
  view: 'Xem',
  edit: 'Chỉnh sửa chi tiết thông tin',
  create: 'Tạo mới',
  delete: 'Xoá',
  clone: 'Clone',
  import: 'Import',
  export: 'Export',
  changePassword: 'Đổi mật khẩu',
  assign: 'Chuyển',
  duplicate: 'Check trùng',
};
