export const HEADER = [
  { label: 'NgayTao', key: 'NgayTao' },
  { label: 'TrangThai*', key: 'TrangThai*' },
  { label: 'DanhMuc*', key: 'DanhMuc*' },
  { label: 'DiaChi*', key: 'DiaChi*' },
  { label: 'Duong*', key: 'Duong*' },
  { label: 'PhuongXa*', key: 'PhuongXa*' },
  { label: 'QuanHuyen*', key: 'QuanHuyen*' },
  { label: 'TinhThanhPho*', key: 'TinhThanhPho*' },
  { label: 'TenSales*', key: 'TenSales*' },
  { label: 'SoDienThoaiSales*', key: 'SoDienThoaiSales*' },
  { label: 'TenChuNha', key: 'TenChuNha' },
  { label: 'SoDienThoaiChuNha', key: 'SoDienThoaiChuNha' },
  { label: 'ThienChi', key: 'ThienChi' },
  { label: 'Gia*', key: 'Gia*' },
  { label: 'PhiMoiGioi*', key: 'PhiMoiGioi*' },
  { label: 'NoiBoBan', key: 'NoiBoBan' },
  { label: 'Huong', key: 'Huong' },
  { label: 'ViTri*', key: 'ViTri*' },
  { label: 'ChieuNgang*', key: 'ChieuNgang*' },
  { label: 'ChieuDai*', key: 'ChieuDai*' },
  { label: 'DienTich(m2)', key: 'DienTich(m2)' },
  { label: 'DienTichCongNhan(m2)*', key: 'DienTichCongNhan(m2)*' },
  { label: 'PhongTam', key: 'PhongTam' },
  { label: 'NhaVeSinh', key: 'NhaVeSinh' },
  { label: 'SoHong', key: 'SoHong' },
  { label: 'KetCau*', key: 'KetCau*' },
  { label: 'GhiChu', key: 'GhiChu' },
];
export const EXAMPLE = [
  {
    NgayTao: '06/10/2022',
    'TrangThai*': 'Đang bán',
    'DanhMuc*': 'Căn hộ chung cư',
    'DiaChi*': 75,
    'Duong*': 'Đường Cờ Xanh',
    'PhuongXa*': 'Thị trấn Cờ Đỏ',
    'QuanHuyen*': 'Huyện Cờ Đỏ',
    'TinhThanhPho*': 'Thành phố Cần Thơ',
    'SoDienThoaiSales*': '0974732332',
    'TenSales*': 'Lê Văn Tuấn',
    SoDienThoaiChuNha: '0984474744',
    TenChuNha: 'Lê Văn Phong',
    ThienChi: 'Yes',
    'Gia*': 666,
    'PhiMoiGioi*': 10,
    NoiBoBan: 'Yes',
    Huong: 'Tây Bắc',
    'ViTri*': 'Mặt tiền',
    'ChieuNgang*': 10,
    'ChieuDai*': 10,
    ['DienTich(m2)']: 100,
    ['DienTichCongNhan(m2)*']: 100,
    PhongTam: 4,
    NhaVeSinh: 4,
    SoHong: 'Yes',
    'KetCau*': 'Nhà có kết cấu chắc chắn',
    GhiChu: 'Nhà mặt phố phù hợp mục đích kinh doanh',
  },
];
